
default:
    echo "Learning reference link https://blog.yoshuawuyts.com/in-place-construction-seems-surprisingly-simple/"
    just --list

run:
    cargo run

# simulate the client and test the main
client msg='hello world':
    echo {{msg}} | nc 127.0.0.1 8000 -u

# move old main code to example as a record
back new_name='m0':
    mkdir -p examples
    cp src/main.rs examples/{{new_name}}.rs

ex name='m0':
    cargo run --example {{name}}

