
default:
    echo "Learning reference link https://bencher.dev/learn/benchmarking/rust/criterion/"
    just --list

run:
    cargo run

# benchmark code
bench:
    cargo bench

back new_name='m0':
    mkdir -p examples
    cp src/main.rs examples/{{new_name}}.rs

ex name='m0':
    cargo run --example {{name}}

